# permissions for end users to view podinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podinfo-viewer-role
rules:
- apiGroups:
  - info.podinfo-operator.io
  resources:
  - podinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - info.podinfo-operator.io
  resources:
  - podinfoes/status
  verbs:
  - get
