
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - info.podinfo-operator.io
  resources:
  - podinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - info.podinfo-operator.io
  resources:
  - podinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - info.podinfo-operator.io
  resources:
  - podinfoes/status
  verbs:
  - get
  - patch
  - update
