apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: podinfo-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Podinfo is the Schema for the podinfoes API
      displayName: Podinfo
      kind: Podinfo
      name: podinfos.info.podinfo-operator.io
      version: v1alpha1
  description: Operator for podinfoes
  displayName: podinfo-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - podinfo
  links:
  - name: Podinfo Operator
    url: https://podinfo-operator.domain
  maturity: alpha
  provider:
    name: asdf
  version: 0.0.0
